# Generated by Django 5.0.6 on 2024-05-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrpition',
            new_name='description',
        ),
    ]
